### ISSUE TITLE
Support volume name generate interface

### ISSUE THREAD

**Issue by sanjid133** [kubernetes-csi/csi-test#103]
There are some cloud provider like **Linode**, has some constraints on volume (like volume id is integer number). So, It will be helpful to add a `VolumeNameGenerate interface{}`, then pass it to the controller.

**Comment by sanjid133** [comment]
cc: @displague @tamalsaha

https://github.com/pharmer/csi-test/pull/1

**Comment by tamalsaha** [comment]
Linode's csi driver https://github.com/displague/csi-linode

**Comment by tamalsaha** [comment]
@@saad-ali, do you mind taking a look?

**Comment by saad-ali** [comment]
Sorry I don't follow. Can you clarify what behavior you want from what component? What will `VolumeNameGenerate interface{}` do?

**Comment by lpabon** [comment]
I think we can add this as a switch to csi-sanity. This switch would then notify csi-sanity to use a specific name type. This is a good suggestion and an easy fix.

**Comment by displague** [comment]
If you can provide a little more detail on how you would have this implemented, I'll send the PR.

**Comment by lpabon** [comment]
i think adding an implementation for volume generation would be good, but needs to be part of csi-test repo so that it can be used from csi-sanity tool.

**Comment by lpabon** [comment]
This does feel weird, that the spec says it is a string but really they are numbers. I think this really should go to CSI spec to modify the documentation and explain that the CO should create names using string-numbers only.

**Comment by tamalsaha** [comment]
@lpabon / @displague, any updates on this one?

**Comment by displague** [comment]
I worked around this problem with a tests-only hack.

https://github.com/linode/linode-blockstorage-csi-driver/blob/e312ce00cf75ed243c4e545d73403c395ff1489d/pkg/common/idhelpers.go#L25-L47

I would still like to see a proper solution so I could include early validation around the requested ids.
Actual Linode users specifying "afakeid" will find that the translated integer value is invalid 99.9999%  of the time 🎲, leading to API responses that the VolumeID/NodeID specified was not found, which is effectively true.
