### ISSUE TITLE
Need tests around string limits

### ISSUE THREAD

**Issue by bswartz** [kubernetes-csi/csi-test#107]
The CSI spec says that strings should not exceed 128 bytes and string maps should not exceed 4096 bytes. It's not clear where this enforcement should happen, but it would be nice to have tests that validate that plugin don't return strings that exceed these limits and negative tests that exceed these limits.

More importantly, we need tests that create volumes/snapshots using the maximum length names, to catch plugins which are using the name somewhere that can't handle 128 bytes.

**Comment by Gambler13** [comment]
Any chance to make the name length configurable?
I'm writing a CSI driver, but the storage provider supports only a length of 64 bytes.

**Comment by pohly** [comment]
@Gambler13 as discussed in https://github.com/kubernetes-csi/csi-test/pull/110#pullrequestreview-151913616, the CO is allowed to pass a name that is longer than 64 characters. If your CSI driver can't support that, it may fail randomly with different COs.

Or are you planning to only use the CSI driver with a CO that is guaranteed to use shorter names?

**Comment by bswartz** [comment]
@Gambler13 The CSI spec doesn't require that you can store the name, only that you can accept names up to 128 bytes long. If your storage is limited, then for correctness sake you can hash the input string down to 128 bits (with MD5, for example), and store the hash instead, which requires only 32 bytes in base-16 encoding. This solution is less pretty, but will meet the specification.

**Comment by Gambler13** [comment]
Of course, but the test suite is checking the volume name after the VolumeCreate method. If I truncate the name to 64 bytes before calling the storage API, the test still fails.
Anyway, I can live with it. Thank you for your fast answers.

**Comment by pohly** [comment]
Gambler13 <notifications@github.com> writes:
> Of course, but the test suite is checking the volume name after the
> VolumeCreate method. If I truncate the name to 64 bytes before calling
> the storage API, the test still fails.

Which check fails? Can you link to the line in the test?

**Comment by bswartz** [comment]
Truncation is not correct. The semantic value of the volume name is that it should be used for idempotency. If you get 2 create requests with the same name, you should treat the second one as a retry of the first operation. If you get requests with different names, _even with the same 127 byte prefix_, you should create 2 separate volumes. You can only implement these semantics if you either store the whole 128 byte name, or you store a reasonably strong (128 bit, cryptographic) hash of the name.
