### ISSUE TITLE
Need test cases for unicode volume/snapshot names

### ISSUE THREAD

**Issue by bswartz** [kubernetes-csi/csi-test#108]
Although it's not clearly stated, the CSI spec allows Unicode names to be specified for volumes and snapshot. A naively implement plugin might take the suggested name and use it somewhere where Unicode characters aren't supported, and the bug might not get caught if all of the test cases use ASCII names. We should send some non-ASCII names to the plugin and expect success.

**Comment by msau42** [comment]
Doesn't seem like we want to pursue this in the csi spec.
/close
