### ISSUE TITLE
enable K8S PR dashboard ("Gubernator")

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/csi-test#113]
https://k8s-gubernator.appspot.com/pr is a useful overview of PRs that need attention. Repositories explicitly need to be enabled to show up there, see https://github.com/kubernetes/test-infra/blob/master/gubernator/README.md#adding-a-repository-to-the-pr-dashboard

Can we do that for csi-test and all other repos under kubernetes-csi?

**Comment by lpabon** [comment]
That's a good question, let me check it out. We should also bring it to the attention of the rest of the kubernetes-csi community

**Comment by pohly** [comment]
Came up again on Slack today and dims created the necessary web hooks. I'll close it once I see it working.

/assign

**Comment by pohly** [comment]
It works... and it promptly reminded me that some of my PRs are still pending ;-}
