### ISSUE TITLE
Is this repo actively maintained?

### ISSUE THREAD

**Issue by wk8** [kubernetes-csi/csi-test#126]
I'm a sr dev with Docker, and could make some time to help on this repo; it seems to me that having a simple, canonical way of testing CSI drivers' compliance would be of great value to the community.

However, it's not obvious what the state of this repo is; is it still actively maintained? And/or are more maintainers welcome? Where could I best start helping?

Thanks!

**Comment by pohly** [comment]
It is maintained, albeit perhaps not as actively as it could be, due to lack of time. I myself recently became a Kubernetes member and approver for this repo, but have been busy with other things.

So help would definitely be welcome.

**Comment by wk8** [comment]
Thanks for the reply @pohly . Anything in particular that's more urgent?

**Comment by pohly** [comment]
Not really. You might want to have a look at the list of open issues. Some of them might need help or became stale and can be closed.
