### ISSUE TITLE
sanity: support different addresses for controller and node operations

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/csi-test#142]
Currently the sanity pkg connects to the CSI driver at a single address and expects to find all services there. Not all CSI drivers are deployed like that and some might not even support all services in the same binary. Therefore I propose to have Config.Address (as it is now) and to add an optional Config.ControllerAddress that gets used if set when connecting to the controller.

**Comment by shay-berman** [comment]
I think its good input
Some driver may implement node\identity in golang but controller in python (for what ever reason). Allow to run only the node tests will be used full for such use case.

In addition(I think in some way its related), is there a way to selectively specify the APIs we want to run sanity with?  For example csi-node but only nodepublish.

**Comment by pohly** [comment]
Why does it matter whether the controller is written in Python? As long as it implements the gRPC API correctly, it can be tested with csi-sanity.

Regarding running only some tests: the `csi-sanity` command is a Ginkgo test suite. You can use `-ginkgo.focus` to run only some tests.

**Comment by shay-berman** [comment]
Hi @pohly , I just gave an example where the controller and the node will not be on a single address (because one written in python and the other in golang).   So this issue is important.

About ginko.focus, yes you right, but can u do it also from the csi-test CLI?

**Comment by pohly** [comment]
> I just gave an example where the controller and the node will not be on a single address (because one written in python and the other in golang). So this issue is important.

That makes sense. What I don't understand is the "allow to run only the node tests" part.

> About ginko.focus, yes you right, but can u do it also from the csi-test CLI?

Yes, because it is a Ginkgo test suite. The Ginko runner is only a wrapper which passes those parameters through to the test suite. Try `csi-sanity -help`...
