### ISSUE TITLE
Add support for generating a JUnit XML test report file

### ISSUE THREAD

**Issue by rodrigc** [kubernetes-csi/csi-test#146]
It would be very handy if csi-sanity and other test suites can be enhanced to generate
a JUnit XML test report file:

https://onsi.github.io/ginkgo/#generating-junit-xml-output

This will help integrate with the Jenkins test report viewer

**Comment by pohly** [comment]
You want this to be added to the csi-sanity command, right?

When defining your own test suite, you can already add the necessary code, nothing in csi-test must be modified for that.

/help-wanted

**Comment by rodrigc** [comment]
@pohly Yes, my request is for this to be added to the csi-sanity command.
