### ISSUE TITLE
Starting v0.3.4 release asset binaries don't work in Alpine container

### ISSUE THREAD

**Issue by antonfisher** [kubernetes-csi/csi-test#149]
Hi, working on our CI, I noticed this.

Release v0.3.0-4 works fine but starting from release v0.3.4 asset binaries on [releases page](https://github.com/kubernetes-csi/csi-test/releases) doesn't work in an Alpine container. The same is true for 1.0.2.

It seems like assets have been built with different flags than [Makefile](https://github.com/kubernetes-csi/csi-test/blob/release-0.3/Makefile#L30) has because if I build the image from sources (using `Makefile`) it works in Alpine.

There are two one-liners to demonstrate the issue (I used `Dockerfile.mock` from the repo).
v0.3.0-4 (works):
```bash
$ curl -L https://github.com/kubernetes-csi/csi-test/releases/download/v0.3.0-4/csi-sanity-v0.3.0-4.linux.amd64.tar.gz | tar -xvz && mv csi-sanity/csi-sanity bin/mock && docker build -f Dockerfile.mock -t csi-sanity-local --no-cache . && docker run --rm -it csi-sanity-local
... curl output ...
Sending build context to Docker daemon  11.83MB
Step 1/5 : FROM alpine
... docker output ...
Successfully tagged csi-sanity-local:latest
--- FAIL: TestSanity (0.00s)
	sanity_test.go:53: --csi.endpoint must be provided with an CSI endpoint <--- IT WORKS
FAIL
```
v0.3.4 (doesn't work):
```bash
$ curl -L https://github.com/kubernetes-csi/csi-test/releases/download/v0.3.4/csi-sanity-v0.3.4.linux.amd64.tar.gz | tar -xvz && mv csi-sanity/csi-sanity bin/mock && docker build -f Dockerfile.mock -t csi-sanity-local --no-cache . && docker run --rm -it csi-sanity-local
... curl output ...
Sending build context to Docker daemon  11.89MB
Step 1/5 : FROM alpine
... docker output ...
Successfully tagged csi-sanity-local:latest
standard_init_linux.go:190: exec user process caused "no such file or directory" <--- DOESN'T WORK
```

Solutions that helped me:
- build binaries using `Makefile`
- use `ubuntu` container
- manually link missed libraries in my container `RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2`

Not sure that asset binaries supposed to work in Alpine, or manual image build is a recommended way to go.

This issue is similar to https://github.com/kubernetes-csi/csi-test/issues/127.

Thank you.

[EDIT]
- removed `quay.io/k8scsi/mock-driver` mention, thought it is csi-sanity container.

**Comment by msau42** [comment]
We no longer include binaries as part of the release so programs will need to be built separately
/close
