### ISSUE TITLE
csi-sanity -h csi-sanity: command not found

### ISSUE THREAD

**Issue by yamunadevins** [kubernetes-csi/csi-test#175]
Hi,

I have pulled the latest image using docker pull , it is only pulling mock driver, csi-sanity command is throwing not found , how to invoke the csi-sanity command
quay.io/k8scsi/mock-driver                 
quay.io/k8scsi/csi-node-driver-registrar   
quay.io/k8scsi/driver-registrar            
k8s.gcr.io/kube-proxy                      
k8s.gcr.io/kube-apiserver                  
k8s.gcr.io/kube-scheduler                  
k8s.gcr.io/kube-controller-manager         
quay.io/calico/node                        
quay.io/calico/cni                         
quay.io/calico/kube-controllers            
k8s.gcr.io/coredns                         
quay.io/k8scsi/hostpathplugin              
k8s.gcr.io/etcd                            
quay.io/coreos/etcd                        
k8s.gcr.io/pause                           

I have these images running in kubernetes master node

**Comment by pohly** [comment]
There are no pre-built csi-sanity command binaries anymore. You need to checkout out the source code and then build it yourself.

**Comment by yamunadevins** [comment]
While trying to compile the cmd folder , there is no binary executable. Could you please elaborate how to utilize this package.

**Comment by okartau** [comment]
What do you mean by "compile the cmd folder" ?
I do it like this:
- clone this repository
- type `make` (you need Go building capability)
- after successful build there should be `cmd/csi-sanity/csi-sanity` as the binary (I got a 12MB file)
- copy it to your GOPATH/bin or wherever you want to run it from

**Comment by yamunadevins** [comment]
> * Go building capability
When i issue make command , this is the issue i am facing 

mkdir -p bin
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o ./bin/mock ./mock/main.go
'CGO_ENABLED' is not recognized as an internal or external command,
operable program or batch file.
make: *** [bin/mock] Error 1


My Go env:
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\shanmy\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\shanmy\go
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\xxx=/tmp/go-build

**Comment by okartau** [comment]
It appears you try build on Windows OS.
The current build setup seems not to be suitable for building on Windows, and that is overall style in many kubernetes-related repositories (actually, without even explicit documenting it), that the build and use is meant on, and verified on Linux OS (not so sure do those repos get verified on other Unix-like systems at all?)
Do you have specific requirement to build (and run) on Windows?
It's probably easier to switch to Linux (or try some system enabling Linux semantics on top of Windows) than to port build of this repo here (and many connecting parts) to Windows semantics.

**Comment by yamunadevins** [comment]
After switching to linux,
make
mkdir -p bin
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-X main.version=v1.1.1-11-gb7da8ae -extldflags "-static"' -o ./bin/mock-driver ./cmd/mock-driver
make -C cmd/csi-sanity all
make[1]: Entering directory '/root/csi-test/cmd/csi-sanity'
go test -ldflags "-w -X github.com/kubernetes-csi/csi-test/cmd/csi-sanity.VERSION=v1.1.0-60-gb7da8ae -extldflags '-z relro -z now'" -c -o csi-sanity
make[1]: Leaving directory '/root/csi-test/cmd/csi-sanity'

Make command succeeded without errors , but i am not able to find the executable

**Comment by yamunadevins** [comment]
Thanks for all the inputs
