### ISSUE TITLE
csi sanity "Node Service"."should work" test seems to be more restrictive than the spec

### ISSUE THREAD

**Issue by alexanderKhaustov** [kubernetes-csi/csi-test#194]
CreateVolumeRequest in the test does not containt AccessibilityRequirements
https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/node.go#L632
which is allowed in the spec:
https://github.com/container-storage-interface/spec/blob/master/lib/go/csi/csi.pb.go#L833
However, in this case "the SP MAY choose where the provisioned volume is accessible from" rather than required to. 

If there's no universally accessible disk provided by the SP the most logical thing to do seems to fail the CreateVolume which will fail the test:
https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/node.go#L648

One might suggest that SP choose any of the available zones and provide a volume, but in this case the test might fail further at
https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/node.go#L684
since the node that the driver runs on might well end up in the different accessibility zone which will make publishing the volume on the node impossible

**Comment by pohly** [comment]
csi-sanity simulates a CO with a single node, with (where required) that node name being take from the driver's node info. So I guess the right solution would be to always set AccessibilityRequirements?

Do you think you can come up with a PR?

**Comment by alexanderKhaustov** [comment]
> csi-sanity simulates a CO with a single node, with (where required) that node name being take from the driver's node info. So I guess the right solution would be to always set AccessibilityRequirements?
Seems so
 
> Do you think you can come up with a PR?
In a few days, yeah
