### ISSUE TITLE
[feature request] add a 'skip' option

### ISSUE THREAD

**Issue by ZeroMagic** [kubernetes-csi/csi-test#207]
Recently, we add the sanity test to find lots of issues in driver implementation. 
We think it is very useful. But during testing, we find that there are some scenarios which do not apply to our product. 

For example, capacity is not supported in blobfuse driver, so the test `Controller Service CreateVolume [It] should fail when requesting to create a volume with already existing name and different capacity. ` will always fail.

Another example is that the CI machine is not an an on-premise VM in Azure. Then we can not mount azure disk volume to the CI machine. So the test `Node Service
/home/travis/gopath/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/tests.go:44
  should work [It]` will always fail.

A 'Skip' option will be very helpful for us to choose the suitable tests.

**Comment by pohly** [comment]
You can use `-ginkgo.skip` to disable tests that don't work for your driver.

**Comment by ZeroMagic** [comment]
It is awesome! Thanks.

**Comment by cornfeedhobo** [comment]
@pohly How do you do that when the tests are run as a unittest?

**Comment by pohly** [comment]
`go test ... -args -ginkgo.skip="Something"`
