### ISSUE TITLE
Go mod breaks importing

### ISSUE THREAD

**Issue by avorima** [kubernetes-csi/csi-test#231]
Since Go 1.13 (I think) it is required that a `v2` release or higher contain the major version in the module directive (https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

Since this is not set, it effectively breaks updating to `v2.3.0`:

```
go get github.com/kubernetes-csi/csi-test@v2.3.0
...
require github.com/kubernetes-csi/csi-test: version "v2.3.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

The solution is rather simple, but it may be a breaking change for some users.

**Comment by pohly** [comment]
Sounds like we should do a v3.0.0 and bump the import paths in the source code and in the `go.mod` file. Agreed?

We were discussing other breaking API changes. That would be a good time to do them.

**Comment by Ntr0** [comment]
As I have just created a PR, I can easily update it to bump v3 ;)

**Comment by Ntr0** [comment]
https://github.com/kubernetes-csi/csi-test/pull/232

**Comment by msau42** [comment]
@pohly right now our infra uses go1.12.1. should we update to 1.13 as well?
