### ISSUE TITLE
Controller should be optional

### ISSUE THREAD

**Issue by ktarplee** [kubernetes-csi/csi-test#281]
According to the CSI spec, the controller is actually optional.  I would like a way to run the tests without assuming the controller exists.  Only the NodeServer and IdentityServer are present in my OCI plugin.

From the [spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#getplugincapabilities)
> CONTROLLER_SERVICE indicates that the Plugin provides RPCs for
      the ControllerService. Plugins SHOULD provide this capability.
      In rare cases certain plugins MAY wish to omit the
      ControllerService entirely from their implementation, but such
      SHOULD NOT be the common case.

I tried adding `-ginkgo.focus Node` but there are still tests that fail due to calling controller RPCs such as 

```txt
• Failure [0.002 seconds]
Node Service
/code/oss/csi-test/pkg/sanity/tests.go:44
  NodeStageVolume
  /code/oss/csi-test/pkg/sanity/node.go:424
    should fail when no volume capability is provided [It]
    /code/oss/csi-test/pkg/sanity/node.go:475

    Unexpected error:
        <*status.statusError | 0xc000430c30>: {
            Code: 12,
            Message: "unknown service csi.v1.Controller",
            Details: nil,
            XXX_NoUnkeyedLiteral: {},
            XXX_unrecognized: nil,
            XXX_sizecache: 0,
        }
        rpc error: code = Unimplemented desc = unknown service csi.v1.Controller
    occurred
```

**Comment by pohly** [comment]
That's a valid issue. The controller is needed to create volumes that then can be used during the node operations. Another approach for specifying valid volumes will be needed when testing without controller. Patches welcome...

**Comment by ktarplee** [comment]
I will work on it.  I might also try to tackle #214 at the same time.

**Comment by onokatio** [comment]
It is still problem.
