### ISSUE TITLE
List volume  : should fail when an invalid starting_token is passed

### ISSUE THREAD

**Issue by pzheng1025** [kubernetes-csi/csi-test#323]
The error log is  
List volume  
   should fail when an invalid starting_token is passed [It]

  /go/src/github.com/datenlord/datenlord/csi-test/pkg/sanity/controller.go:193
    Expected
        <codes.Code>: 3
    to equal
        <codes.Code>: 10

Question:
What is the reason that for this case the gRPC status code should be ABORTED instead of INVALID_ARGUMENT?

**Comment by pohly** [comment]
Zheng Pan <notifications@github.com> writes:
> What is the reason that for this case the gRPC status code should be
> ABORTED instead of INVALID_ARGUMENT?

The spec contains ABORTED for this case:
https://github.com/container-storage-interface/spec/blob/master/spec.md#listvolumes-errors

Invalid starting_token 	10 ABORTED 	Indicates that starting_token is not valid.

**Comment by pzheng1025** [comment]
Thank you for sharing the spec. I have gone through that. 
Could you share some sights about why it should return ABORTED instead of INVALID_ARGUMENT like other "invalid argument" cases?

**Comment by pohly** [comment]
Zheng Pan <notifications@github.com> writes:
> Could you share some sights about why it should return ABORTED instead
> of INVALID_ARGUMENT like other "invalid argument" cases?

I don't know for sure. I suppose the spec authors wanted to distinguish
between "invalid argument" = "your program is broken" and "invalid
token" = "your program is fine, just get a new token".

**Comment by pzheng1025** [comment]
Thank you.
