### ISSUE TITLE
Resource cleanup failed due to fast create-delete process

### ISSUE THREAD

**Issue by tyichye19** [kubernetes-csi/csi-test#346]
In some storage systems when trying to create a volume from an existing volume we have to wait for the copy process to be finish before we try to delete one of the volumes.
The community tests does not wait and therefor some tests sometimes fail on Teardown step due to fast create-delete process.
Is there any test configuration that we can use in order to wait before executing the Teardown step and between delete operations?

**Comment by msau42** [comment]
I believe the CreateVolume() call should not return until the volume is ready.

**Comment by tyichye19** [comment]
It's not part of the SPEC and therefore the CSI driver is not waiting for the storage.
It's the client's responsibility to check the volume status on his storage.

**Comment by msau42** [comment]
I think there is an implicit assumption that if a call returns success, that means the operation is complete and volume is ready to use. The only exception is when taking a snapshot, which is explicitly called out in the spec.

cc @bswartz @xing-yang 
Do you think we need to make this explicit?

**Comment by bswartz** [comment]
Yeah my understanding is that, if you create volume B from volume A, and the CreateVolume call returns success, you can immediately call DeleteVolume on A and volume B should be fine. If this isn't clear we can sharpen up the language.

No matter what we say, the driver can play games if it wants to background some operations, but that's entirely on the driver's end. It still has to pretend to succeed the deletion of A even if it's copying from data from A to B in the background, and then it's incumbent on the driver to remember to actually wipe out A when it's no longer needed. Furthermore a creation of a new A must not be confused with the still-existing A that the driver lied about and said was deleted. These are hacks that can be worked into the driver if you're clever enough but I wouldn't recommend it.

A better way for drivers that have a lot of work to do at create volume time (when cloning) is to either allow the GRPC client to timeout and retry over and over, or have the driver explicitly return an error fast if it's working on the copy operation and rely on the sidecar's endless retry loop to eventually find out when the copy operation is done.

**Comment by bswartz** [comment]
Do we have a section somewhere for "implementer notes" where we can provide advice for how to deal with some of these pitfalls? I think the spec and existing sidecar implementations are clear enough, but I've spent a lot of time on this stuff. New implementers would benefit from a "top 10 pitfalls" type of list somewhere

**Comment by xing-yang** [comment]
We can add these to CSI driver docs?

**Comment by msau42** [comment]
Near the top of https://github.com/container-storage-interface/spec/blob/master/spec.md, there's descriptions on general error handling, timeouts, idempotency, etc. That may be a good place to add something.

**Comment by oriyarde** [comment]
> I think there is an implicit assumption that if a call returns success, that means the operation is complete and volume is ready to use. The only exception is when taking a snapshot, which is explicitly called out in the spec.

> Yeah my understanding is that, if you create volume B from volume A, and the CreateVolume call returns success, you can immediately call DeleteVolume on A and volume B should be fine. If this isn't clear we can sharpen up the language.

I think there is a nuance in the meaning of "is ready to use" here.
In our storage system, a volume clone can be ready for I/O as soon as it is created, but its source volume cannot be deleted until the background copy is complete.
so this suggested implementation requirement here would be a disadvantage for our users.

could we we allow both approaches in the spec, as was done for snapshots?

**Comment by oriyarde** [comment]
I guess we'll have to support source deletion before the background copy is completed
