### ISSUE TITLE
ListSnapshot: support secrets

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/csi-test#356]
https://github.com/kubernetes-csi/csi-test/blob/b9a7786589336fd54e8e1d3a1fa01df1f63c1d8f/pkg/sanity/sanity.go#L39-L51 does not have an entry for ListSnapshot and invocations of that function in https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/controller.go lack secrets.

This should be added because the spec allows it and drivers may need it.

/help

**Comment by jskazinski** [comment]
Just letting other knows, I have made changes to address this issue and I am working on a pull request. My ListSnapshots tests are now getting the correct secrets.
