### ISSUE TITLE
NodeExpandVolume test checks optional fields

### ISSUE THREAD

**Issue by outscale-mdr** [kubernetes-csi/csi-test#388]
Hello,

I've seen that this [test](https://github.com/kubernetes-csi/csi-test/blob/ac644842c1a03ec828b7473d2e538d4462074455/pkg/sanity/node.go#L807) checks if `CapacityBytes` returned by `NodeExpandVolume`  is correct. However in the CSI spec, this is just [optional](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeexpandvolume).

Best regards,
Maxime

**Comment by gnufied** [comment]
I think this may have been an oversight.

**Comment by pohly** [comment]
@outscale-mdr: can you perhaps prepare a PR?

**Comment by outscale-mdr** [comment]
Yes sure, I will see what I can do

**Comment by outscale-mdr** [comment]
Actually, I mixed between controllers and nodes. The code is correct because the check is done for ControllerExpandVolume and not for NodeExpandVolume.

Nothing to do, sorry for that !
