### ISSUE TITLE
pkg/sanity usage as non-root user

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/csi-test#73]
When following https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/README.md and running "go test" as normal user (!), tests involving mounting/unmounting fail because those are privileged operations.

Running "sudo go test" isn't a good solution, because then building also runs as root. This is not desirable and can also fail because the environment variables for Go end up being different.

My workaround was to have mount/unmount wrapper scripts that run just the mount and unmount command under pseudo. I can submit a PR with just those scripts (see below), but then one still has to remember to update PATH.

I wonder whether this isn't something that the test framework itself should take care of. Any thoughts?

```
#!/bin/sh

# Get rid of our wrapper script by setting a standard search PATH.
PATH=/usr/bin:/bin:/usr/sbin:/sbin

if [ $(id -u) != 0 ]; then
   exec sudo $(basename $0) "$@"
else
   exec $(basename $0) "$@"
fi
```

**Comment by lpabon** [comment]
If this is run from `go test` then as a user I would suggest building a binary and using that as sudo. csi-test should not know what user it is used as.

**Comment by pohly** [comment]
Luis Pabón <notifications@github.com> writes:
> If this is run from `go test` then as a user I would suggest building
> a binary and using that as sudo.

I was aware of that option and found it that rather inconvenient. "dlv
test" also doesn't work out-of-the-box.

But okay, let's close this.
