### ISSUE TITLE
NodePublishVolume test doesn't set volume attributes returned by CreateVolume

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-test#88]
The CSI spec is a little confusing. It says that the VolumeAttributes field is optional, but must match the attributes of the volume:
```
       // Attributes of the volume to publish. This field is OPTIONAL and  
        // MUST match the attributes of the Volume identified by                               
        // `volume_id`.                   
        VolumeAttributes     map[string]string 
```

**Comment by saad-ali** [comment]
The intention is that if it is returned by the volume plugin on a `CreateVolumeResponse` it must be passed on on subsequent `PublishVolume` requests. csi-test should verify this behavior, and optionally we should clarify the wording of this in the spec.
