### ISSUE TITLE
Sanity tests may not always cleanup

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-test#89]
There are two problems with the tests:
1. The CreateVolume request could succeed, but subsequent validation could fail.  DeleteVolume() is skipped in those cases so the volume never gets cleaned up.
2. Almost all the tests call CreateVolume with volume id "sanity".  It would be better to use unique names for every test case to avoid potential false positives and issues where a previously failing test causes a subsequent test to fail because the volume already exists.

**Comment by pohly** [comment]
Reusing the same volume ID also prevents running specs in parallel. I'm encountering that right now.

I'll work on a fix.

**Comment by pohly** [comment]
@msau42 should each test *case* have a unique name or also each test *run*? In other words, is is okay to have fixed names like `sanity-controller-single-with-capacity` (unique for each test case) or do we need random names like `sanity-44de2d24-7f9a-11e8-8a87-77571b0768c3`?

I prefer `sanity-controller-single-with-capacity`. It makes it easier to follow and repeat tests, but of course the downside is that one might have to clean up after an aborted test run which left volumes behind.

**Comment by pohly** [comment]
Does it make sense to run the exact same test twice, under different names?

See NodeStageVolume and NodeUnstageVolume - both run testFullWorkflowSuccess.

**Comment by pohly** [comment]
Not twice - four times!

**Comment by msau42** [comment]
If the driver is persisting volume names to disk, then the issue could still exist.  Mine only keeps the names in memory, so it's fine for me.

I think the tests could also be restructured a bit to add the volume cleanup to an aftereach so that it will always happen even if the test errors early.

**Comment by pohly** [comment]
Okay, so let's use a unique suffix. I'll also add the cleanup and restructure the tests so that the testFullWorkflowSuccess test only runs once.
